In [1]:
import pandas as pd

In [6]:
df_train = pd.read_csv("data/fashion-mnist_train.csv")
df_train.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df_test = pd.read_csv("data/fashion-mnist_test.csv")
df_test.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Preprocessing

In [14]:
#TODO
# From Instructions:
# - Technically "optional" and depends on specific methods chosen to implement
# - Examples of preprocessing: 
# 1. converting 28x28 matrices into vectors of 784 features (ZL: don't really get this since it seems like the pandas df already has a single row for all 784 features)
# 2. Dimensional reduction methods (e.g. PCA) before clustering or SVM (ZL: likely need to do this since we are doing clustering)
# 3. Scale features for methods that are sensitive to different scales (ZL: aren't all the features already on the same scale of 0-255? Maybe just scale to 0-1.)

## 1. Data Processing and Unsupervised Learning.

**(a) Compute and report a frequency table of the outcome variable in both training and
testing data.**

In [9]:
train_freq = df_train['label'].value_counts()

In [10]:
test_freq = df_test['label'].value_counts()

In [11]:
freq_table = pd.DataFrame({
    'Train Count': train_freq,
    'Test Count': test_freq
})
freq_table['Train %'] = (freq_table['Train Count'] / train_freq.sum() * 100).round(2)
freq_table['Test %']  = (freq_table['Test Count'] / test_freq.sum() * 100).round(2)
freq_table

   Train Count  Test Count  Train %  Test %
0         6000        1000     10.0    10.0
1         6000        1000     10.0    10.0
2         6000        1000     10.0    10.0
3         6000        1000     10.0    10.0
4         6000        1000     10.0    10.0
5         6000        1000     10.0    10.0
6         6000        1000     10.0    10.0
7         6000        1000     10.0    10.0
8         6000        1000     10.0    10.0
9         6000        1000     10.0    10.0

**(b) Perform two clustering algorithms to the training data.
– Use a systematic approach (e.g., gap statistic, silhouette statistic) to find the
optimal number of clusters (if applicable).
– What is the dominating label in each of these clusters?
– Do your clusters help to separate the labels? Comment on the results**

## 2. Multi-class Classification Model

**Choose four of the methods we discussed in class to do multi-class classification. Similar to coding assignment 4, some of the methods were presented for binary classification,
but you are free to extend and use them for multi-class classification (e.g. you can use
One-vs-Rest). Make sure you describe your approach.**

In [ ]:
#TODO

**Report the overall classification error. Also, please provide enough supporting information, e.g. tables/figures, to demonstrate the fit of the models.**

In [13]:
#TODO